### ISSUE TITLE
Can you open source RRPD and NRBP? 

### ISSUE THREAD

**Issue by ymingsu** [weizhou-geek/Dehazed-Image-Quality-Evaluation#1]
The RRPD and NRBP codes you proposed in your paper _Dehazed Image Quality Evaluation: From Partial Discrepancy to Blind Perception_ are not included, only the code for RRIQA is included.

**Comment by weizhou-geek** [comment]
The compute_rriqa_demo is for the RRPD. And the NRBP is based on the features from RRPD, with regression models.
